// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSe_5yYfcL9a98NZ5NjcAtptMi-LbKmdw',
    appId: '1:697743747159:web:50ebd3578bdc6f12f5db12',
    messagingSenderId: '697743747159',
    projectId: 'procoup-6a3f3',
    authDomain: 'procoup-6a3f3.firebaseapp.com',
    storageBucket: 'procoup-6a3f3.firebasestorage.app',
    measurementId: 'G-VCRPXX56QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SrigqopJX4Q3OjBCjiz0v6c2sg6_t_s',
    appId: '1:697743747159:android:6037be3172ae9304f5db12',
    messagingSenderId: '697743747159',
    projectId: 'procoup-6a3f3',
    storageBucket: 'procoup-6a3f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYDFTIV9wbw1-l--6HJsub-VqyUR3u5Hw',
    appId: '1:697743747159:ios:9dafc00199e2a3d0f5db12',
    messagingSenderId: '697743747159',
    projectId: 'procoup-6a3f3',
    storageBucket: 'procoup-6a3f3.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSe_5yYfcL9a98NZ5NjcAtptMi-LbKmdw',
    appId: '1:697743747159:web:5e537f59b821ba10f5db12',
    messagingSenderId: '697743747159',
    projectId: 'procoup-6a3f3',
    authDomain: 'procoup-6a3f3.firebaseapp.com',
    storageBucket: 'procoup-6a3f3.firebasestorage.app',
    measurementId: 'G-BFZJLT6199',
  );
}
